font_family Comic Code
font_size 15
enable_audio_bell no
cursor_blink_interval 0.5
cursor_shape block

# Dracula Theme cho Kitty
foreground            #f8f8f2
background            #282a36
selection_foreground  #f8f8f2
selection_background  #282a36

url_color #8be9fd

map ctrl+shift+equal change_font_size all +0.5
map ctrl+shift+minus change_font_size all -0.5

# Màu sắc cho con trỏ (Cursor)
cursor            #f8f8f0
cursor_text_color background
